https://basedosdados.org/dataset/br-ibge-censo-demografico?bdm_table=microdados_domicilio_2000

In [36]:
# sigla_uf	STRING	Sigla da Unidade da Federação
# id_municipio	STRING	ID Município - IBGE 7 Dígitos
# situacao_domicilio	INT64	Situação do domicílio
# v0110	INT64	Total de homens
# v0111	INT64	Total de mulheres
# v0202	INT64	Tipo do domicílio
# v0203	INT64	Total de cômodos
# v0205	INT64	Condição do domicílio
# v0207	INT64	Forma de abastecimento de água
# v0209	INT64	Total de banheiros
# v0212	INT64	Coleta de lixo
# v0213	INT64	Iluminação elétrica
# v0214	INT64	Existência de rádio
# v0215	INT64	Existência de geladeira ou freezer
# v0216	INT64	Existência de videocassete
# v0217	INT64	Existência de máquina de lavar roupa
# v0218	INT64	Existência de forno de microondas
# v0219	INT64	Existência de linha telefônica instalada
# v0220	INT64	Existência de microcomputador
# v0221	INT64	Quantidade existente de televisores
# v0222	INT64	Quantidade existente de automóveis para uso particular
# v0223	INT64	Quantidade existente de aparelhos de ar condicionado
# v7100	INT64	Total de moradores no domicílio
# v1112	INT64	Existência de iluminação pública
# v1113	INT64	Existência de calçamento/pavimentação

# v7616	INT64	Total de rendimentos do domicílio particular

In [37]:
import pandas as pd

In [38]:
df = pd.read_csv('data/censo-2010.csv')

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   sigla_uf            1000 non-null   object
 1   situacao_domicilio  1000 non-null   int64
 2   comodos             983 non-null    float64
 3   condicao_domicilio  983 non-null    float64
 4   banheiros           983 non-null    float64
 5   moradores           1000 non-null   int64
 6   homens              1000 non-null   int64
 7   mulheres            1000 non-null   int64
 8   agua                983 non-null    float64
 9   coleta_lixo         983 non-null    float64
 10  iluminacao          983 non-null    float64
 11  radio               983 non-null    float64
 12  geladeira           983 non-null    float64
 13  videocassete        983 non-null    float64
 14  maquina_lavar       983 non-null    float64
 15  microondas          983 non-null    float64
 16  telefone            983 non-null    float64
 17  computador          983 non-null    float64
 18  televisores         983 non-null    float64
 19  automoveis          983 non-null    float64
 20  ar_condicionado     983 non-null    float64
 21  iluminacao_publica  1000 non-null   int64
 22  pavimentacao        995 non-null    float64
 23  rendimento          995 non-null    float64
dtypes: float64(18), int64(5), object(1)
memory usage: 187.6+ KB

In [40]:
df.isna().sum()

sigla_uf               0
situacao_domicilio     0
comodos               17
condicao_domicilio    17
banheiros             17
moradores              0
homens                 0
mulheres               0
agua                  17
coleta_lixo           17
iluminacao            17
radio                 17
geladeira             17
videocassete          17
maquina_lavar         17
microondas            17
telefone              17
computador            17
televisores           17
automoveis            17
ar_condicionado       17
iluminacao_publica     0
pavimentacao           5
rendimento             5
dtype: int64

In [41]:
from sklearn.linear_model import LinearRegression

In [42]:
from sklearn.preprocessing import LabelEncoder

df['sigla_uf'] = LabelEncoder().fit_transform(df['sigla_uf'])

In [43]:
df_fillna = df.fillna(0)

In [44]:
X = df_fillna.drop('rendimento', axis=1)
y = df_fillna['rendimento']

In [45]:
X

,sigla_uf,situacao_domicilio,comodos,condicao_domicilio,banheiros,moradores,homens,mulheres,agua,coleta_lixo,...,videocassete,maquina_lavar,microondas,telefone,computador,televisores,automoveis,ar_condicionado,iluminacao_publica,pavimentacao
0,0,1,7.0,1.0,1.0,7,4,3,2.0,3.0,...,2.0,2.0,2.0,2.0,2.0,0.0,0.0,0.0,7,3.0
1,0,1,5.0,1.0,1.0,4,1,3,1.0,1.0,...,1.0,2.0,2.0,2.0,2.0,1.0,0.0,0.0,4,3.0
2,0,1,5.0,1.0,0.0,6,3,3,2.0,1.0,...,2.0,2.0,2.0,1.0,2.0,1.0,1.0,0.0,6,3.0
3,0,1,3.0,1.0,0.0,1,0,1,2.0,1.0,...,2.0,2.0,2.0,2.0,2.0,0.0,0.0,0.0,1,3.0
4,0,1,3.0,1.0,0.0,9,4,5,2.0,3.0,...,2.0,2.0,2.0,1.0,2.0,1.0,1.0,0.0,9,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0,1,3.0,1.0,0.0,2,1,1,1.0,1.0,...,2.0,2.0,2.0,2.0,2.0,1.0,0.0,0.0,2,3.0
996,0,1,4.0,1.0,0.0,3,2,1,1.0,1.0,...,2.0,2.0,2.0,2.0,2.0,0.0,0.0,0.0,3,3.0
997,0,1,2.0,5.0,0.0,4,2,2,3.0,1.0,...,2.0,2.0,2.0,2.0,2.0,0.0,0.0,0.0,4,3.0
998,0,1,4.0,1.0,0.0,6,2,4,1.0,1.0,...,2.0,2.0,2.0,2.0,2.0,1.0,0.0,0.0,6,3.0
999,0,1,1.0,1.0,0.0,3,2,1,1.0,1.0,...,2.0,2.0,2.0,2.0,2.0,1.0,0.0,0.0,3,3.0

In [46]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [52]:
lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)
y_pred = lin_reg.predict(X_test)

from sklearn.metrics import mean_squared_error,r2_score

np.sqrt(mean_squared_error(y_test, y_pred))

1629.3897252991637

In [53]:
r2_score(y_test, y_pred)

0.20912909740752528

In [50]:
df.describe()

,sigla_uf,situacao_domicilio,comodos,condicao_domicilio,banheiros,moradores,homens,mulheres,agua,coleta_lixo,...,maquina_lavar,microondas,telefone,computador,televisores,automoveis,ar_condicionado,iluminacao_publica,pavimentacao,rendimento
count,1000.0,1000.000000,983.000000,983.000000,983.000000,1000.0000,1000.000000,1000.000000,983.000000,983.000000,...,983.000000,983.00000,983.000000,983.000000,983.000000,983.000000,983.000000,1000.0000,995.000000,995.000000
mean,0.0,1.267000,4.033571,1.508647,0.351984,4.0280,2.071000,1.957000,1.782299,2.285860,...,1.917599,1.97355,1.729400,1.982706,0.759919,0.107833,0.076297,4.0280,2.714573,632.027136
std,0.0,0.442614,1.798928,1.208286,0.600588,2.0512,1.312891,1.296469,0.608337,1.571991,...,0.275114,0.16055,0.444496,0.130431,0.764101,0.335554,0.415187,2.0512,1.121824,1310.810115
min,0.0,1.000000,1.000000,1.000000,0.000000,1.0000,0.000000,0.000000,1.000000,1.000000,...,1.000000,1.00000,1.000000,1.000000,0.000000,0.000000,0.000000,1.0000,1.000000,0.000000
25%,0.0,1.000000,3.000000,1.000000,0.000000,3.0000,1.000000,1.000000,1.000000,1.000000,...,2.000000,2.00000,1.000000,2.000000,0.000000,0.000000,0.000000,3.0000,3.000000,170.500000
50%,0.0,1.000000,4.000000,1.000000,0.000000,4.0000,2.000000,2.000000,2.000000,1.000000,...,2.000000,2.00000,2.000000,2.000000,1.000000,0.000000,0.000000,4.0000,3.000000,330.000000
75%,0.0,2.000000,5.000000,1.000000,1.000000,5.0000,3.000000,3.000000,2.000000,3.000000,...,2.000000,2.00000,2.000000,2.000000,1.000000,0.000000,0.000000,5.0000,3.000000,684.500000
max,0.0,2.000000,15.000000,6.000000,5.000000,14.0000,9.000000,9.000000,3.000000,7.000000,...,2.000000,2.00000,2.000000,2.000000,7.000000,3.000000,6.000000,14.0000,9.000000,25000.000000