https://basedosdados.org/dataset/br-ibge-censo-demografico?bdm_table=microdados_domicilio_2000

In [43]:
# sigla_uf	STRING	Sigla da Unidade da Federação
# id_municipio	STRING	ID Município - IBGE 7 Dígitos
# situacao_domicilio	INT64	Situação do domicílio
# v0110	INT64	Total de homens
# v0111	INT64	Total de mulheres
# v0202	INT64	Tipo do domicílio
# v0203	INT64	Total de cômodos
# v0205	INT64	Condição do domicílio
# v0207	INT64	Forma de abastecimento de água
# v0209	INT64	Total de banheiros
# v0212	INT64	Coleta de lixo
# v0213	INT64	Iluminação elétrica
# v0214	INT64	Existência de rádio
# v0215	INT64	Existência de geladeira ou freezer
# v0216	INT64	Existência de videocassete
# v0217	INT64	Existência de máquina de lavar roupa
# v0218	INT64	Existência de forno de microondas
# v0219	INT64	Existência de linha telefônica instalada
# v0220	INT64	Existência de microcomputador
# v0221	INT64	Quantidade existente de televisores
# v0222	INT64	Quantidade existente de automóveis para uso particular
# v0223	INT64	Quantidade existente de aparelhos de ar condicionado
# v7100	INT64	Total de moradores no domicílio
# v1112	INT64	Existência de iluminação pública
# v1113	INT64	Existência de calçamento/pavimentação

# v7616	INT64	Total de rendimentos do domicílio particular

In [44]:
import pandas as pd

In [45]:
df = pd.read_csv('data/censo-2000.csv')

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 24 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   sigla_uf            5000 non-null   object
 1   situacao_domicilio  5000 non-null   int64
 2   comodos             4967 non-null   float64
 3   condicao_domicilio  4967 non-null   float64
 4   banheiros           4967 non-null   float64
 5   moradores           5000 non-null   int64
 6   homens              5000 non-null   int64
 7   mulheres            5000 non-null   int64
 8   agua                4967 non-null   float64
 9   coleta_lixo         4967 non-null   float64
 10  iluminacao          4967 non-null   float64
 11  radio               4967 non-null   float64
 12  geladeira           4967 non-null   float64
 13  videocassete        4967 non-null   float64
 14  maquina_lavar       4967 non-null   float64
 15  microondas          4967 non-null   float64
 16  telefone            4967 non-null   float64
 17  computador          4967 non-null   float64
 18  televisores         4967 non-null   float64
 19  automoveis          4967 non-null   float64
 20  ar_condicionado     4967 non-null   float64
 21  iluminacao_publica  5000 non-null   int64
 22  pavimentacao        4598 non-null   float64
 23  rendimento          5000 non-null   int64
dtypes: float64(17), int64(6), object(1)
memory usage: 937.6+ KB

In [47]:
df.isna().sum()

sigla_uf                0
situacao_domicilio      0
comodos                33
condicao_domicilio     33
banheiros              33
moradores               0
homens                  0
mulheres                0
agua                   33
coleta_lixo            33
iluminacao             33
radio                  33
geladeira              33
videocassete           33
maquina_lavar          33
microondas             33
telefone               33
computador             33
televisores            33
automoveis             33
ar_condicionado        33
iluminacao_publica      0
pavimentacao          402
rendimento              0
dtype: int64

In [48]:
from sklearn.linear_model import LinearRegression

In [49]:
from sklearn.preprocessing import LabelEncoder

df['sigla_uf'] = LabelEncoder().fit_transform(df['sigla_uf'])

In [50]:
df_fillna = df.fillna(0)

In [51]:
X = df_fillna.drop('rendimento', axis=1)
y = df_fillna['rendimento']

In [52]:
X

,sigla_uf,situacao_domicilio,comodos,condicao_domicilio,banheiros,moradores,homens,mulheres,agua,coleta_lixo,...,videocassete,maquina_lavar,microondas,telefone,computador,televisores,automoveis,ar_condicionado,iluminacao_publica,pavimentacao
0,25,1,6.0,1.0,1.0,4,2,2,1.0,1.0,...,2.0,2.0,1.0,1.0,2.0,1.0,1.0,0.0,4,2.0
1,5,1,6.0,1.0,1.0,5,4,1,2.0,3.0,...,2.0,2.0,2.0,2.0,2.0,1.0,0.0,0.0,5,1.0
2,13,1,6.0,3.0,0.0,10,6,4,2.0,3.0,...,2.0,2.0,2.0,2.0,2.0,2.0,0.0,0.0,10,3.0
3,25,1,6.0,5.0,1.0,5,3,2,1.0,1.0,...,1.0,2.0,2.0,1.0,2.0,2.0,0.0,0.0,5,1.0
4,17,2,5.0,4.0,1.0,4,3,1,2.0,3.0,...,2.0,2.0,2.0,2.0,2.0,1.0,0.0,0.0,4,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,25,1,6.0,1.0,1.0,5,3,2,1.0,1.0,...,1.0,2.0,2.0,2.0,2.0,1.0,1.0,0.0,5,2.0
4996,25,1,4.0,1.0,1.0,3,2,1,1.0,1.0,...,2.0,1.0,2.0,2.0,2.0,1.0,0.0,0.0,3,3.0
4997,17,1,6.0,1.0,1.0,6,3,3,1.0,1.0,...,2.0,2.0,2.0,2.0,2.0,2.0,1.0,0.0,6,3.0
4998,22,1,6.0,1.0,1.0,5,3,2,1.0,1.0,...,1.0,1.0,2.0,1.0,2.0,1.0,0.0,0.0,5,3.0
4999,18,1,9.0,1.0,2.0,3,2,1,1.0,1.0,...,1.0,1.0,1.0,1.0,2.0,2.0,1.0,2.0,3,1.0

In [63]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

In [64]:
from sklearn.preprocessing import StandardScaler

std_scaler = StandardScaler()
std_scaler.fit(X_train)
X_train_sc = std_scaler.transform(X_train)
X_test_sc = std_scaler.transform(X_test)

In [65]:
lin_reg = LinearRegression()
lin_reg.fit(X_train_sc, y_train)
y_pred = lin_reg.predict(X_test_sc)

from sklearn.metrics import mean_squared_error,r2_score

np.sqrt(mean_squared_error(y_test, y_pred))

1687.4712595119386

In [67]:
r2_score(y_test, y_pred)

0.33408631565530433

In [56]:
df.describe()

,sigla_uf,situacao_domicilio,comodos,condicao_domicilio,banheiros,moradores,homens,mulheres,agua,coleta_lixo,...,maquina_lavar,microondas,telefone,computador,televisores,automoveis,ar_condicionado,iluminacao_publica,pavimentacao,rendimento
count,5000.000000,5000.000000,4967.000000,4967.000000,4967.000000,5000.000000,5000.000000,5000.000000,4967.000000,4967.000000,...,4967.000000,4967.00000,4967.000000,4967.000000,4967.000000,4967.000000,4967.000000,5000.000000,4598.000000,5000.000000
mean,15.716600,1.206600,5.716932,1.782766,1.095832,3.867600,1.904400,1.963200,1.313670,1.769881,...,1.692571,1.82726,1.635796,1.907187,1.271391,0.388967,0.107308,3.867600,1.996520,1044.483000
std,7.530022,0.404906,2.287792,1.300934,0.799011,1.973841,1.272943,1.247139,0.588742,1.383841,...,0.461475,0.37806,0.481255,0.290199,0.891876,0.641013,0.455822,1.973841,1.442234,1868.188934
min,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,1.000000,1.000000,...,1.000000,1.00000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,10.000000
25%,10.000000,1.000000,4.000000,1.000000,1.000000,3.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,2.00000,1.000000,2.000000,1.000000,0.000000,0.000000,3.000000,1.000000,268.750000
50%,17.000000,1.000000,5.000000,1.000000,1.000000,4.000000,2.000000,2.000000,1.000000,1.000000,...,2.000000,2.00000,2.000000,2.000000,1.000000,0.000000,0.000000,4.000000,1.000000,500.000000
75%,23.000000,1.000000,7.000000,3.000000,1.000000,5.000000,3.000000,3.000000,1.000000,2.000000,...,2.000000,2.00000,2.000000,2.000000,2.000000,1.000000,0.000000,5.000000,3.000000,1050.000000
max,26.000000,2.000000,20.000000,6.000000,8.000000,18.000000,10.000000,12.000000,3.000000,7.000000,...,2.000000,2.00000,2.000000,2.000000,8.000000,7.000000,6.000000,18.000000,9.000000,42500.000000

In [82]:
from sklearn.ensemble import RandomForestRegressor

forest_reg = RandomForestRegressor(random_state=42)

forest_reg.fit(X_train, y_train)
y_pred = forest_reg.predict(X_test)

r2_score(y_test, y_pred)

0.3069314989484774